name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies from source
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute test command from source
        run: |
          python3 KeePwn.py --help

      - name: Install package with pipx
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install .

      - name: Execute test command with pipx
        run: |
          KeePwn --help